FROM node:12-alpine
RUN yarn global add gatsby-cli

# install dependencies
WORKDIR /app
COPY package.json package.json
RUN yarn install --no-lockfile

# bundle source and blog posts on build
ONBUILD COPY . /app
