FROM node:16-alpine
RUN yarn global add gatsby-cli

# install dependencies
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn
RUN gatsby telemetry --disable

# bundle source and blog posts on build
ONBUILD COPY . .
