# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Deploy to CloudFront

on:
  push:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  push_to_s3_origin:
    name: Push production Gatsby build to S3 origin for CloudFront
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Build/Deploy production Gatsy files
        uses: borales/actions-yarn@v3.0.0
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          cmd: deploy # will run `yarn deploy` command with above env
