# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: S3/Dockerhub Publish

on:
  push:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  # build blog node.js bundle
  build_blog:
    name: Build Blog
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install Node.js Dependencies
        uses: bahmutov/npm-install@HEAD
      - name: Cache Gatsby Build
        id: cache-gatsby-build
        uses: actions/cache@v3
        with:
          path: |
            public
            .cache
          key: ${{ runner.os }}-gatsby-build-${{ hashFiles('yarn.lock', 'gatsby-config.ts') }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build-
      - name: Build Gatsby Blog
        env:
          DISABLE_WEBPACK_ANALYSER: 'true'
        run: |
          yarn gatsby telemetry --disable 2> /dev/null
          yarn build
      - name: Run tests
        run: yarn test
      - name: Store Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}-gatsby-build-${{ github.run_id }}
          path: public
  # release updates version/changelog in repo and pushes tags/release to github
  release_blog:
    name: Release Blog
    runs-on: ubuntu-latest
    # GITHUB_TOKEN permissions for semantic-release
    permissions:
      contents: write
      pull-requests: write
      issues: write
    outputs:
      release-version: ${{ steps.semantic.outputs.release-version }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          # fetch all git history to speed up @semantic-release/commit-analyzer
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install Node.js Dependencies
        uses: bahmutov/npm-install@HEAD
      - name: Semantic Release
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn semantic-release -r ${{ github.repositoryUrl }}
  # push blog release to aws s3
  push_blog_to_s3:
    needs: [build_blog, release_blog]
    name: Push Blog to S3
    runs-on: ubuntu-latest
    if: needs.release_blog.outputs.release-version != ''
    steps:
      - name: Restore Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ runner.os }}-gatsby-build-${{ github.run_id }}
          path: public
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy Gatsby Blog to S3 origin
        uses: jonelantha/gatsby-s3-action@v1
        with:
          dest-s3-bucket: blog.imranc.io
          cloudfront-id-to-invalidate: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_BLOG }}
  # push blog release to dockerhub
  push_blog_to_dockerhub:
    needs: [build_blog, release_blog]
    name: Push Blog to Dockerhub
    runs-on: ubuntu-latest
    if: needs.release_blog.outputs.release-version != ''
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: imrancio/blog
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{needs.release_blog.outputs.release-version}},enable={{is_default_branch}}
      - name: Restore Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ runner.os }}-gatsby-build-${{ github.run_id }}
          path: public
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
